name = "vulnetix"
compatibility_date = "2025-04-01"
compatibility_flags = ["cf_botmanagement_default"]
upload_source_maps = true
main = "./dist/worker/index.js"

[assets]
directory = "./dist/client/"
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"

[limits]
cpu_ms = 3000

[[d1_databases]]
binding = "d1db"
database_name = "vulnetix"
database_id = "9c8382d1-394e-4897-b746-2dacd790b83e"

[[r2_buckets]]
binding = 'r2artifacts'
bucket_name = 'artifacts'

[[r2_buckets]]
binding = 'r2webhooks'
bucket_name = 'webhooks'

[[queues.producers]]
binding = "scanqueue"
queue = "scan-queue"

[ai]
binding = "llm"
