name = "vulnetix"
main = "src/main.js"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
account_id = "e302589106b4c4287aebe65763eb4f80"
workers_dev = true

[limits]
cpu_ms = 3000

[[d1_databases]]
binding = "d1db"
database_name = "vulnetix"
database_id = "15dc7c29-05a9-46c2-b87b-89b1a4f32d33"

[[r2_buckets]]
binding = 'r2artifacts'
bucket_name = 'artifacts'

[[r2_buckets]]
binding = 'r2webhooks'
bucket_name = 'webhooks'
