CREATE TABLE "new_findings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "findingId" TEXT NOT NULL,
    "memberEmail" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "modifiedAt" INTEGER NOT NULL,
    "publishedAt" INTEGER,
    "detectionTitle" TEXT NOT NULL,
    "purl" TEXT,
    "cpe" TEXT,
    "databaseReviewed" INTEGER,
    "cve" TEXT,
    "aliases" TEXT,
    "cwes" TEXT,
    "packageName" TEXT NOT NULL,
    "packageVersion" TEXT,
    "packageLicense" TEXT,
    "vendor" TEXT,
    "product" TEXT,
    "packageEcosystem" TEXT,
    "sourceCodeUrl" TEXT,
    "exploitsJSON" TEXT,
    "knownExploitsJSON" TEXT,
    "cisaDateAdded" INTEGER,
    "knownRansomwareCampaignUse" TEXT,
    "fixVersion" TEXT,
    "fixAutomatable" INTEGER,
    "vulnerableVersionRange" TEXT,
    "maliciousSource" TEXT,
    "abandoned" INTEGER,
    "squattedPackage" TEXT,
    "referencesJSON" TEXT,
    "spdxId" TEXT,
    "cdxId" TEXT
);
INSERT INTO "new_findings" (
        "abandoned",
        "aliases",
        "category",
        "cdxId",
        "cisaDateAdded",
        "cpe",
        "createdAt",
        "cve",
        "cwes",
        "databaseReviewed",
        "detectionTitle",
        "exploitsJSON",
        "findingId",
        "fixAutomatable",
        "fixVersion",
        "knownExploitsJSON",
        "knownRansomwareCampaignUse",
        "maliciousSource",
        "memberEmail",
        "modifiedAt",
        "packageEcosystem",
        "packageLicense",
        "packageName",
        "packageVersion",
        "product",
        "publishedAt",
        "purl",
        "referencesJSON",
        "source",
        "sourceCodeUrl",
        "spdxId",
        "squattedPackage",
        "vendor",
        "vulnerableVersionRange"
    )
SELECT "abandoned",
    "aliases",
    "category",
    "cdxId",
    "cisaDateAdded",
    "cpe",
    "createdAt",
    "cve",
    "cwes",
    "databaseReviewed",
    "detectionTitle",
    "exploitsJSON",
    "findingId",
    "fixAutomatable",
    "fixVersion",
    "knownExploitsJSON",
    "knownRansomwareCampaignUse",
    "maliciousSource",
    "memberEmail",
    "modifiedAt",
    "packageEcosystem",
    "packageLicense",
    "packageName",
    "packageVersion",
    "product",
    "publishedAt",
    "purl",
    "referencesJSON",
    "source",
    "sourceCodeUrl",
    "spdxId",
    "squattedPackage",
    "vendor",
    "vulnerableVersionRange"
FROM "findings";
DROP TABLE "findings";
ALTER TABLE "new_findings"
    RENAME TO "findings";
DROP TABLE "triage_activity";
CREATE TABLE "triage_activity" (
    "findingKey" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" INTEGER NOT NULL,
    "triagedAt" INTEGER,
    "lastObserved" INTEGER NOT NULL,
    "seen" INTEGER NOT NULL,
    "seenAt" INTEGER,
    "cvssVector" TEXT,
    "cvssScore" TEXT,
    "epssPercentile" TEXT,
    "epssScore" TEXT,
    "ssvc" TEXT,
    "remediation" TEXT,
    "analysisState" TEXT NOT NULL,
    "analysisJustification" TEXT,
    "analysisResponse" TEXT,
    "analysisDetail" TEXT,
    "triageAutomated" INTEGER NOT NULL DEFAULT 0,
    "memberEmail" TEXT
);
