-- RedefineTables
PRAGMA defer_foreign_keys = ON;
PRAGMA foreign_keys = OFF;
CREATE TABLE "new_findings" (
    "findingId" TEXT NOT NULL,
    "memberEmail" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "modifiedAt" INTEGER NOT NULL,
    "publishedAt" INTEGER,
    "detectionTitle" TEXT NOT NULL,
    "purl" TEXT,
    "cpe" TEXT,
    "databaseReviewed" INTEGER,
    "cve" TEXT,
    "aliases" TEXT,
    "cwes" TEXT,
    "packageName" TEXT NOT NULL,
    "packageVersion" TEXT,
    "packageLicense" TEXT,
    "vendor" TEXT,
    "product" TEXT,
    "packageEcosystem" TEXT,
    "sourceCodeUrl" TEXT,
    "exploitsJSON" TEXT,
    "knownExploitsJSON" TEXT,
    "cisaDateAdded" INTEGER,
    "knownRansomwareCampaignUse" TEXT,
    "fixVersion" TEXT,
    "fixAutomatable" INTEGER,
    "vulnerableVersionRange" TEXT,
    "maliciousSource" TEXT,
    "abandoned" INTEGER,
    "squattedPackage" TEXT,
    "referencesJSON" TEXT,
    "spdxId" TEXT,
    "cdxId" TEXT
);
INSERT INTO "new_findings" (
        "abandoned",
        "aliases",
        "category",
        "cdxId",
        "cisaDateAdded",
        "cpe",
        "createdAt",
        "cve",
        "cwes",
        "databaseReviewed",
        "detectionTitle",
        "exploitsJSON",
        "findingId",
        "fixAutomatable",
        "fixVersion",
        "knownExploitsJSON",
        "knownRansomwareCampaignUse",
        "maliciousSource",
        "memberEmail",
        "modifiedAt",
        "packageEcosystem",
        "packageLicense",
        "packageName",
        "packageVersion",
        "product",
        "publishedAt",
        "purl",
        "referencesJSON",
        "source",
        "sourceCodeUrl",
        "spdxId",
        "squattedPackage",
        "vendor",
        "vulnerableVersionRange"
    )
SELECT "abandoned",
    "aliases",
    "category",
    "cdxId",
    "cisaDateAdded",
    "cpe",
    "createdAt",
    "cve",
    "cwes",
    "databaseReviewed",
    "detectionTitle",
    "exploitsJSON",
    "findingId",
    "fixAutomatable",
    "fixVersion",
    "knownExploitsJSON",
    "knownRansomwareCampaignUse",
    "maliciousSource",
    "memberEmail",
    "modifiedAt",
    "packageEcosystem",
    "packageLicense",
    "packageName",
    "packageVersion",
    "product",
    "publishedAt",
    "purl",
    "referencesJSON",
    "source",
    "sourceCodeUrl",
    "spdxId",
    "squattedPackage",
    "vendor",
    "vulnerableVersionRange"
FROM "findings";
DROP TABLE "findings";
ALTER TABLE "new_findings"
    RENAME TO "findings";
CREATE TABLE "new_triage_activity" (
    "findingId" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "lastObserved" INTEGER NOT NULL,
    "seen" INTEGER NOT NULL,
    "seenAt" INTEGER,
    "cvssVector" TEXT,
    "cvssScore" TEXT,
    "epssPercentile" TEXT,
    "epssScore" TEXT,
    "ssvc" TEXT,
    "remediation" TEXT,
    "analysisState" TEXT NOT NULL,
    "analysisJustification" TEXT,
    "analysisResponse" TEXT,
    "analysisDetail" TEXT,
    "triageAutomated" INTEGER NOT NULL DEFAULT 0,
    "memberEmail" TEXT
);
INSERT INTO "new_triage_activity" (
        "analysisDetail",
        "analysisJustification",
        "analysisResponse",
        "analysisState",
        "createdAt",
        "cvssScore",
        "cvssVector",
        "epssPercentile",
        "epssScore",
        "findingId",
        "lastObserved",
        "memberEmail",
        "remediation",
        "seen",
        "seenAt",
        "ssvc",
        "triageAutomated"
    )
SELECT "analysisDetail",
    "analysisJustification",
    "analysisResponse",
    "analysisState",
    "createdAt",
    "cvssScore",
    "cvssVector",
    "epssPercentile",
    "epssScore",
    "findingId",
    "lastObserved",
    "memberEmail",
    "remediation",
    "seen",
    "seenAt",
    "ssvc",
    "triageAutomated"
FROM "triage_activity";
DROP TABLE "triage_activity";
ALTER TABLE "new_triage_activity"
    RENAME TO "triage_activity";
CREATE UNIQUE INDEX "findings_findingId_key" ON "findings"("findingId");
CREATE UNIQUE INDEX "triage_activity_findingId_key" ON "triage_activity"("findingId");
PRAGMA foreign_keys = ON;
PRAGMA defer_foreign_keys = OFF;
