ALTER TABLE "sarif_results"
  ADD "automationDetailsId" TEXT;
ALTER TABLE "sarif_results"
  ADD "rulesetName" TEXT;
ALTER TABLE "sarif_results"
  ADD "level" TEXT;
ALTER TABLE "sarif_results"
  ADD "description" TEXT;
ALTER TABLE "sarif_results"
  ADD "helpMarkdown" TEXT;
ALTER TABLE "sarif_results"
  ADD "securitySeverity" TEXT;
ALTER TABLE "sarif_results"
  ADD "precision" TEXT;
ALTER TABLE "sarif_results"
  ADD "tags" TEXT;
