CREATE TABLE "CVEMetadata" (
    "cveId" TEXT NOT NULL PRIMARY KEY,
    "dataVersion" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "datePublished" INTEGER NOT NULL,
    "dateUpdated" INTEGER,
    "dateReserved" INTEGER,
    "vectorString" TEXT,
    "title" TEXT NOT NULL,
    "sourceAdvisoryRef" TEXT,
    "affectedVendor" TEXT,
    "affectedProduct" TEXT,
    "affectedVersionsJSON" TEXT,
    "cpesJSON" TEXT,
    "cnaOrgId" TEXT NOT NULL,
    "fileLinkId" INTEGER NOT NULL
);
CREATE TABLE "CVENumberingAuthrity" (
    "orgId" TEXT NOT NULL PRIMARY KEY,
    "shortName" TEXT NOT NULL
);
CREATE TABLE "CVEADP" (
    "cveId" TEXT NOT NULL,
    "adpId" TEXT NOT NULL,
    PRIMARY KEY ("cveId", "adpId")
);
CREATE TABLE "AuthorizedDataPublisher" (
    "orgId" TEXT NOT NULL PRIMARY KEY,
    "shortName" TEXT NOT NULL,
    "title" TEXT NOT NULL
);
CREATE TABLE "new_Finding" (
    "uuid" TEXT NOT NULL PRIMARY KEY,
    "findingId" TEXT NOT NULL,
    "orgId" TEXT NOT NULL,
    "memberEmail" TEXT NOT NULL,
    "repoName" TEXT,
    "source" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "createdAt" INTEGER NOT NULL,
    "modifiedAt" INTEGER NOT NULL,
    "publishedAt" INTEGER,
    "detectionTitle" TEXT NOT NULL,
    "purl" TEXT,
    "cpe" TEXT,
    "databaseReviewed" INTEGER,
    "aliases" TEXT,
    "cwes" TEXT,
    "packageName" TEXT NOT NULL,
    "packageVersion" TEXT,
    "packageLicense" TEXT,
    "vendor" TEXT,
    "product" TEXT,
    "packageEcosystem" TEXT,
    "advisoryUrl" TEXT,
    "exploitsJSON" TEXT,
    "knownExploitsJSON" TEXT,
    "cisaDateAdded" INTEGER,
    "knownRansomwareCampaignUse" TEXT,
    "fixVersion" TEXT,
    "fixAutomatable" INTEGER,
    "vulnerableVersionRange" TEXT,
    "malicious" INTEGER,
    "abandoned" INTEGER,
    "squattedPackage" TEXT,
    "referencesJSON" TEXT,
    "timelineJSON" TEXT,
    "spdxId" TEXT,
    "cdxId" TEXT
);
INSERT INTO "new_Finding" (
        "abandoned",
        "aliases",
        "category",
        "cdxId",
        "cisaDateAdded",
        "cpe",
        "createdAt",
        "cwes",
        "databaseReviewed",
        "detectionTitle",
        "exploitsJSON",
        "findingId",
        "fixAutomatable",
        "fixVersion",
        "knownExploitsJSON",
        "knownRansomwareCampaignUse",
        "malicious",
        "memberEmail",
        "modifiedAt",
        "orgId",
        "packageEcosystem",
        "advisoryUrl",
        "packageLicense",
        "packageName",
        "packageVersion",
        "product",
        "publishedAt",
        "purl",
        "referencesJSON",
        "repoName",
        "source",
        "spdxId",
        "squattedPackage",
        "timelineJSON",
        "uuid",
        "vendor",
        "vulnerableVersionRange"
    )
SELECT "abandoned",
    "aliases",
    "category",
    "cdxId",
    "cisaDateAdded",
    "cpe",
    "createdAt",
    "cwes",
    "databaseReviewed",
    "detectionTitle",
    "exploitsJSON",
    "findingId",
    "fixAutomatable",
    "fixVersion",
    "knownExploitsJSON",
    "knownRansomwareCampaignUse",
    "malicious",
    "memberEmail",
    "modifiedAt",
    "orgId",
    "packageEcosystem",
    "sourceCodeUrl" as "advisoryUrl",
    "packageLicense",
    "packageName",
    "packageVersion",
    "product",
    "publishedAt",
    "purl",
    "referencesJSON",
    "repoName",
    "source",
    "spdxId",
    "squattedPackage",
    "timelineJSON",
    "uuid",
    "vendor",
    "vulnerableVersionRange"
FROM "Finding";
DROP TABLE "Finding";
ALTER TABLE "new_Finding"
    RENAME TO "Finding";
