name: Test Action

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binaries
        run: |
          export VERSION="test-$(git rev-parse --short HEAD)"
          ./build.sh
        shell: bash

      - name: Test CLI directly
        run: |
          # Test with valid UUID
          ./bin/vulnetix-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/') --org-id "123e4567-e89b-12d3-a456-426614174000"
        shell: bash

      - name: Test action
        uses: ./
        with:
          org-id: '123e4567-e89b-12d3-a456-426614174000'
