# A sample workflow which sets up periodic SCA scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://www.vulnetix.com/post/github-action/

name: vulnetix-sca

on:
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "vulnetix/vulnetix/.github/workflows/vulnetix-sca-reusable.yml" # OSV v1.7.1
    with:
      # custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "vulnetix/vulnetix/.github/workflows/vulnetix-sca-reusable.yml" # OSV v1.7.1
    with:
      # custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
